name: Build Alpine

on:
    push:
        branches: [master, build_*]
        tags: [v*]
    pull_request:
        branches: [master]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_REPO }}/ustreamer,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            ghcr.io/${{ github.repository }},enable=${{ github.event_name != 'pull_request' }}
          tags: |
            type=ref,event=tag
            type=sha,format=long
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ustreamer
          file: pkg/docker/Dockerfile.alpine
      -
        name: Test
        run: |
          echo version: $(docker run --rm -t ustreamer --version)
          echo -e "features:\n$(docker run --rm -t ustreamer --features)"
      -
        name: Build multi arch
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          file: pkg/docker/Dockerfile.alpine
      -
        name: Push
        if: steps.meta.outputs.tags != ''
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/amd64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: pkg/docker/Dockerfile.alpine
